### ISSUE TITLE
Unknown profiles/rates

### ISSUE THREAD

**Issue by jimmy6616** [robthomson/RF2ETHOS#17]
When selecting various options you are not aware which profile or rate you are editing without looking at the physical switch. Are you able to add the profile / rate number  - Such as per the attached?

Profile - 1, 2, 3 etc
Rates  - 1, 2, 3 etc
![Rates_adj](https://github.com/user-attachments/assets/59ae3786-d316-4061-bdbb-2e857827f3cb)

**Comment by robthomson** [comment]
Simple yes..   Will schedule it in

**Comment by robthomson** [comment]
This code is now working - but will not 'display' until the next release of ethos (1.5.16)
