### ISSUE TITLE
New voices

### ISSUE THREAD

**Issue by jasc76** [robthomson/RF2ETHOS#6]
Hi there :-)

could you do a new voice pack (like amber) ? the current audio is so different to the Ethos voice and also sounds a bit akward....

**Comment by robthomson** [comment]
I am sure I can sort something - I have a full voice pack with same voice files I use.. so also an option.

**Comment by robthomson** [comment]
Just to clarify - I think you want this for rf2status - not rf2ethos.

**Comment by jasc76** [comment]
oops, yes, sure its for status. *sigh*
